# Generated by Django 3.2.25 on 2025-02-20 06:28

import datetime
from django.db import migrations, models
from datetime import timezone
utc = timezone.utc  


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('long_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 2, 27, 6, 28, 13, 376345, tzinfo=utc))),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
